### ISSUE TITLE
"all.min.js" missing

### ISSUE THREAD

**Issue by sorburu** [stevepdp/noise-machine#1]
Hi, nice app, clear and minimal :)
The file all.min.js you are using on the emo is missing here when downloading. There are other js files (main.js, sw.js) that are not used by the app, no? I needed to change the scss folder and file to css.
Best regards,

**Comment by stevepdp** [comment]
Hi sorburu.

I should've provided instructions for building...

Here's what you'll need to do. I'll assume here that you already have Node and npm set up.

**1. `cd` to the project directory**
`cd /path/to/noise-machine-master`

**2. Run npm commands**
```
npm install
npm install gulp -g
npm install http-server -g
```

**3. Run gulp - the default task produces the dist/ export build**
`gulp`

**4. Host**
`cd dist`
`hs`

**5. Browse to http://127.0.0.1:8080 or http://192.168.1.102:8080**
